#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSHOP")]
	public partial class QLSHOPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchitietsanpham(chitietsanpham instance);
    partial void Updatechitietsanpham(chitietsanpham instance);
    partial void Deletechitietsanpham(chitietsanpham instance);
    partial void Insertchitietdonhang(chitietdonhang instance);
    partial void Updatechitietdonhang(chitietdonhang instance);
    partial void Deletechitietdonhang(chitietdonhang instance);
    partial void Insertdanhmuc(danhmuc instance);
    partial void Updatedanhmuc(danhmuc instance);
    partial void Deletedanhmuc(danhmuc instance);
    partial void Insertdonhang(donhang instance);
    partial void Updatedonhang(donhang instance);
    partial void Deletedonhang(donhang instance);
    partial void Insertfeedback(feedback instance);
    partial void Updatefeedback(feedback instance);
    partial void Deletefeedback(feedback instance);
    partial void Insertgiohang(giohang instance);
    partial void Updategiohang(giohang instance);
    partial void Deletegiohang(giohang instance);
    partial void Inserthinhanh(hinhanh instance);
    partial void Updatehinhanh(hinhanh instance);
    partial void Deletehinhanh(hinhanh instance);
    partial void Insertkichthuoc(kichthuoc instance);
    partial void Updatekichthuoc(kichthuoc instance);
    partial void Deletekichthuoc(kichthuoc instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertmausac(mausac instance);
    partial void Updatemausac(mausac instance);
    partial void Deletemausac(mausac instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertvoucher(voucher instance);
    partial void Updatevoucher(voucher instance);
    partial void Deletevoucher(voucher instance);
    partial void Insertvoucher_khachhang(voucher_khachhang instance);
    partial void Updatevoucher_khachhang(voucher_khachhang instance);
    partial void Deletevoucher_khachhang(voucher_khachhang instance);
    #endregion
		
		public QLSHOPDataContext() : 
				base(global::DTO.Properties.Settings.Default.QLSHOPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLSHOPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSHOPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSHOPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSHOPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chitietsanpham> chitietsanphams
		{
			get
			{
				return this.GetTable<chitietsanpham>();
			}
		}
		
		public System.Data.Linq.Table<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this.GetTable<chitietdonhang>();
			}
		}
		
		public System.Data.Linq.Table<danhmuc> danhmucs
		{
			get
			{
				return this.GetTable<danhmuc>();
			}
		}
		
		public System.Data.Linq.Table<donhang> donhangs
		{
			get
			{
				return this.GetTable<donhang>();
			}
		}
		
		public System.Data.Linq.Table<feedback> feedbacks
		{
			get
			{
				return this.GetTable<feedback>();
			}
		}
		
		public System.Data.Linq.Table<giohang> giohangs
		{
			get
			{
				return this.GetTable<giohang>();
			}
		}
		
		public System.Data.Linq.Table<hinhanh> hinhanhs
		{
			get
			{
				return this.GetTable<hinhanh>();
			}
		}
		
		public System.Data.Linq.Table<kichthuoc> kichthuocs
		{
			get
			{
				return this.GetTable<kichthuoc>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<mausac> mausacs
		{
			get
			{
				return this.GetTable<mausac>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<voucher> vouchers
		{
			get
			{
				return this.GetTable<voucher>();
			}
		}
		
		public System.Data.Linq.Table<voucher_khachhang> voucher_khachhangs
		{
			get
			{
				return this.GetTable<voucher_khachhang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietsanpham")]
	public partial class chitietsanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTiet;
		
		private System.Nullable<int> _MaSP;
		
		private System.Nullable<int> _MaKichThuoc;
		
		private System.Nullable<int> _MaMau;
		
		private System.Nullable<int> _SoLuongTon;
		
		private EntitySet<chitietdonhang> _chitietdonhangs;
		
		private EntitySet<giohang> _giohangs;
		
		private EntityRef<kichthuoc> _kichthuoc;
		
		private EntityRef<mausac> _mausac;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietChanging(int value);
    partial void OnMaChiTietChanged();
    partial void OnMaSPChanging(System.Nullable<int> value);
    partial void OnMaSPChanged();
    partial void OnMaKichThuocChanging(System.Nullable<int> value);
    partial void OnMaKichThuocChanged();
    partial void OnMaMauChanging(System.Nullable<int> value);
    partial void OnMaMauChanged();
    partial void OnSoLuongTonChanging(System.Nullable<int> value);
    partial void OnSoLuongTonChanged();
    #endregion
		
		public chitietsanpham()
		{
			this._chitietdonhangs = new EntitySet<chitietdonhang>(new Action<chitietdonhang>(this.attach_chitietdonhangs), new Action<chitietdonhang>(this.detach_chitietdonhangs));
			this._giohangs = new EntitySet<giohang>(new Action<giohang>(this.attach_giohangs), new Action<giohang>(this.detach_giohangs));
			this._kichthuoc = default(EntityRef<kichthuoc>);
			this._mausac = default(EntityRef<mausac>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTiet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTiet
		{
			get
			{
				return this._MaChiTiet;
			}
			set
			{
				if ((this._MaChiTiet != value))
				{
					this.OnMaChiTietChanging(value);
					this.SendPropertyChanging();
					this._MaChiTiet = value;
					this.SendPropertyChanged("MaChiTiet");
					this.OnMaChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="Int")]
		public System.Nullable<int> MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKichThuoc", DbType="Int")]
		public System.Nullable<int> MaKichThuoc
		{
			get
			{
				return this._MaKichThuoc;
			}
			set
			{
				if ((this._MaKichThuoc != value))
				{
					if (this._kichthuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKichThuocChanging(value);
					this.SendPropertyChanging();
					this._MaKichThuoc = value;
					this.SendPropertyChanged("MaKichThuoc");
					this.OnMaKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMau", DbType="Int")]
		public System.Nullable<int> MaMau
		{
			get
			{
				return this._MaMau;
			}
			set
			{
				if ((this._MaMau != value))
				{
					if (this._mausac.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMauChanging(value);
					this.SendPropertyChanging();
					this._MaMau = value;
					this.SendPropertyChanged("MaMau");
					this.OnMaMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongTon", DbType="Int")]
		public System.Nullable<int> SoLuongTon
		{
			get
			{
				return this._SoLuongTon;
			}
			set
			{
				if ((this._SoLuongTon != value))
				{
					this.OnSoLuongTonChanging(value);
					this.SendPropertyChanging();
					this._SoLuongTon = value;
					this.SendPropertyChanged("SoLuongTon");
					this.OnSoLuongTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chitietsanpham_chitietdonhang", Storage="_chitietdonhangs", ThisKey="MaChiTiet", OtherKey="MaChiTietSanPham")]
		public EntitySet<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this._chitietdonhangs;
			}
			set
			{
				this._chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chitietsanpham_giohang", Storage="_giohangs", ThisKey="MaChiTiet", OtherKey="MaChiTietSanPham")]
		public EntitySet<giohang> giohangs
		{
			get
			{
				return this._giohangs;
			}
			set
			{
				this._giohangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kichthuoc_chitietsanpham", Storage="_kichthuoc", ThisKey="MaKichThuoc", OtherKey="MaKichThuoc", IsForeignKey=true)]
		public kichthuoc kichthuoc
		{
			get
			{
				return this._kichthuoc.Entity;
			}
			set
			{
				kichthuoc previousValue = this._kichthuoc.Entity;
				if (((previousValue != value) 
							|| (this._kichthuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._kichthuoc.Entity = null;
						previousValue.chitietsanphams.Remove(this);
					}
					this._kichthuoc.Entity = value;
					if ((value != null))
					{
						value.chitietsanphams.Add(this);
						this._MaKichThuoc = value.MaKichThuoc;
					}
					else
					{
						this._MaKichThuoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("kichthuoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mausac_chitietsanpham", Storage="_mausac", ThisKey="MaMau", OtherKey="MaMau", IsForeignKey=true)]
		public mausac mausac
		{
			get
			{
				return this._mausac.Entity;
			}
			set
			{
				mausac previousValue = this._mausac.Entity;
				if (((previousValue != value) 
							|| (this._mausac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mausac.Entity = null;
						previousValue.chitietsanphams.Remove(this);
					}
					this._mausac.Entity = value;
					if ((value != null))
					{
						value.chitietsanphams.Add(this);
						this._MaMau = value.MaMau;
					}
					else
					{
						this._MaMau = default(Nullable<int>);
					}
					this.SendPropertyChanged("mausac");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitietsanpham", Storage="_sanpham", ThisKey="MaSP", OtherKey="MaSP", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.chitietsanphams.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.chitietsanphams.Add(this);
						this._MaSP = value.MaSP;
					}
					else
					{
						this._MaSP = default(Nullable<int>);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.chitietsanpham = this;
		}
		
		private void detach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.chitietsanpham = null;
		}
		
		private void attach_giohangs(giohang entity)
		{
			this.SendPropertyChanging();
			entity.chitietsanpham = this;
		}
		
		private void detach_giohangs(giohang entity)
		{
			this.SendPropertyChanging();
			entity.chitietsanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietdonhang")]
	public partial class chitietdonhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTiet;
		
		private System.Nullable<int> _MaDonHang;
		
		private System.Nullable<int> _MaChiTietSanPham;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<double> _Gia;
		
		private EntitySet<feedback> _feedbacks;
		
		private EntityRef<chitietsanpham> _chitietsanpham;
		
		private EntityRef<donhang> _donhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietChanging(int value);
    partial void OnMaChiTietChanged();
    partial void OnMaDonHangChanging(System.Nullable<int> value);
    partial void OnMaDonHangChanged();
    partial void OnMaChiTietSanPhamChanging(System.Nullable<int> value);
    partial void OnMaChiTietSanPhamChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    #endregion
		
		public chitietdonhang()
		{
			this._feedbacks = new EntitySet<feedback>(new Action<feedback>(this.attach_feedbacks), new Action<feedback>(this.detach_feedbacks));
			this._chitietsanpham = default(EntityRef<chitietsanpham>);
			this._donhang = default(EntityRef<donhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTiet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTiet
		{
			get
			{
				return this._MaChiTiet;
			}
			set
			{
				if ((this._MaChiTiet != value))
				{
					this.OnMaChiTietChanging(value);
					this.SendPropertyChanging();
					this._MaChiTiet = value;
					this.SendPropertyChanged("MaChiTiet");
					this.OnMaChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", DbType="Int")]
		public System.Nullable<int> MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					if (this._donhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietSanPham", DbType="Int")]
		public System.Nullable<int> MaChiTietSanPham
		{
			get
			{
				return this._MaChiTietSanPham;
			}
			set
			{
				if ((this._MaChiTietSanPham != value))
				{
					if (this._chitietsanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChiTietSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietSanPham = value;
					this.SendPropertyChanged("MaChiTietSanPham");
					this.OnMaChiTietSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chitietdonhang_feedback", Storage="_feedbacks", ThisKey="MaChiTiet", OtherKey="MaChiTietDH")]
		public EntitySet<feedback> feedbacks
		{
			get
			{
				return this._feedbacks;
			}
			set
			{
				this._feedbacks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chitietsanpham_chitietdonhang", Storage="_chitietsanpham", ThisKey="MaChiTietSanPham", OtherKey="MaChiTiet", IsForeignKey=true)]
		public chitietsanpham chitietsanpham
		{
			get
			{
				return this._chitietsanpham.Entity;
			}
			set
			{
				chitietsanpham previousValue = this._chitietsanpham.Entity;
				if (((previousValue != value) 
							|| (this._chitietsanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chitietsanpham.Entity = null;
						previousValue.chitietdonhangs.Remove(this);
					}
					this._chitietsanpham.Entity = value;
					if ((value != null))
					{
						value.chitietdonhangs.Add(this);
						this._MaChiTietSanPham = value.MaChiTiet;
					}
					else
					{
						this._MaChiTietSanPham = default(Nullable<int>);
					}
					this.SendPropertyChanged("chitietsanpham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donhang_chitietdonhang", Storage="_donhang", ThisKey="MaDonHang", OtherKey="MaDonHang", IsForeignKey=true)]
		public donhang donhang
		{
			get
			{
				return this._donhang.Entity;
			}
			set
			{
				donhang previousValue = this._donhang.Entity;
				if (((previousValue != value) 
							|| (this._donhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._donhang.Entity = null;
						previousValue.chitietdonhangs.Remove(this);
					}
					this._donhang.Entity = value;
					if ((value != null))
					{
						value.chitietdonhangs.Add(this);
						this._MaDonHang = value.MaDonHang;
					}
					else
					{
						this._MaDonHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("donhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_feedbacks(feedback entity)
		{
			this.SendPropertyChanging();
			entity.chitietdonhang = this;
		}
		
		private void detach_feedbacks(feedback entity)
		{
			this.SendPropertyChanging();
			entity.chitietdonhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhmuc")]
	public partial class danhmuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanhMuc;
		
		private string _TenDanhMuc;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanhMucChanging(int value);
    partial void OnMaDanhMucChanged();
    partial void OnTenDanhMucChanging(string value);
    partial void OnTenDanhMucChanged();
    #endregion
		
		public danhmuc()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanhMuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanhMuc
		{
			get
			{
				return this._MaDanhMuc;
			}
			set
			{
				if ((this._MaDanhMuc != value))
				{
					this.OnMaDanhMucChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMuc = value;
					this.SendPropertyChanged("MaDanhMuc");
					this.OnMaDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMuc", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenDanhMuc
		{
			get
			{
				return this._TenDanhMuc;
			}
			set
			{
				if ((this._TenDanhMuc != value))
				{
					this.OnTenDanhMucChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMuc = value;
					this.SendPropertyChanged("TenDanhMuc");
					this.OnTenDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_sanpham", Storage="_sanphams", ThisKey="MaDanhMuc", OtherKey="MaDanhMuc")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.donhang")]
	public partial class donhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDonHang;
		
		private System.Nullable<int> _MaKhachHang;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private System.Nullable<System.DateTime> _NgayDuKienGiaoHang;
		
		private System.Nullable<decimal> _TongGia;
		
		private System.Nullable<double> _TongTienSauKhiGiamGia;
		
		private System.Nullable<double> _PhiVanChuyen;
		
		private string _TrangThaiThanhToan;
		
		private string _HinhThucThanhToan;
		
		private string _TrangThaiDonHang;
		
		private string _DiaChiGiaoHang;
		
		private string _MaVoucher;
		
		private string _RecipientPhone;
		
		private EntitySet<chitietdonhang> _chitietdonhangs;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonHangChanging(int value);
    partial void OnMaDonHangChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnNgayDuKienGiaoHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDuKienGiaoHangChanged();
    partial void OnTongGiaChanging(System.Nullable<decimal> value);
    partial void OnTongGiaChanged();
    partial void OnTongTienSauKhiGiamGiaChanging(System.Nullable<double> value);
    partial void OnTongTienSauKhiGiamGiaChanged();
    partial void OnPhiVanChuyenChanging(System.Nullable<double> value);
    partial void OnPhiVanChuyenChanged();
    partial void OnTrangThaiThanhToanChanging(string value);
    partial void OnTrangThaiThanhToanChanged();
    partial void OnHinhThucThanhToanChanging(string value);
    partial void OnHinhThucThanhToanChanged();
    partial void OnTrangThaiDonHangChanging(string value);
    partial void OnTrangThaiDonHangChanged();
    partial void OnDiaChiGiaoHangChanging(string value);
    partial void OnDiaChiGiaoHangChanged();
    partial void OnMaVoucherChanging(string value);
    partial void OnMaVoucherChanged();
    partial void OnRecipientPhoneChanging(string value);
    partial void OnRecipientPhoneChanged();
    #endregion
		
		public donhang()
		{
			this._chitietdonhangs = new EntitySet<chitietdonhang>(new Action<chitietdonhang>(this.attach_chitietdonhangs), new Action<chitietdonhang>(this.detach_chitietdonhangs));
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDonHang
		{
			get
			{
				return this._MaDonHang;
			}
			set
			{
				if ((this._MaDonHang != value))
				{
					this.OnMaDonHangChanging(value);
					this.SendPropertyChanging();
					this._MaDonHang = value;
					this.SendPropertyChanged("MaDonHang");
					this.OnMaDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuKienGiaoHang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDuKienGiaoHang
		{
			get
			{
				return this._NgayDuKienGiaoHang;
			}
			set
			{
				if ((this._NgayDuKienGiaoHang != value))
				{
					this.OnNgayDuKienGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._NgayDuKienGiaoHang = value;
					this.SendPropertyChanged("NgayDuKienGiaoHang");
					this.OnNgayDuKienGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongGia", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> TongGia
		{
			get
			{
				return this._TongGia;
			}
			set
			{
				if ((this._TongGia != value))
				{
					this.OnTongGiaChanging(value);
					this.SendPropertyChanging();
					this._TongGia = value;
					this.SendPropertyChanged("TongGia");
					this.OnTongGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTienSauKhiGiamGia", DbType="Float")]
		public System.Nullable<double> TongTienSauKhiGiamGia
		{
			get
			{
				return this._TongTienSauKhiGiamGia;
			}
			set
			{
				if ((this._TongTienSauKhiGiamGia != value))
				{
					this.OnTongTienSauKhiGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._TongTienSauKhiGiamGia = value;
					this.SendPropertyChanged("TongTienSauKhiGiamGia");
					this.OnTongTienSauKhiGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiVanChuyen", DbType="Float")]
		public System.Nullable<double> PhiVanChuyen
		{
			get
			{
				return this._PhiVanChuyen;
			}
			set
			{
				if ((this._PhiVanChuyen != value))
				{
					this.OnPhiVanChuyenChanging(value);
					this.SendPropertyChanging();
					this._PhiVanChuyen = value;
					this.SendPropertyChanged("PhiVanChuyen");
					this.OnPhiVanChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiThanhToan", DbType="NVarChar(50)")]
		public string TrangThaiThanhToan
		{
			get
			{
				return this._TrangThaiThanhToan;
			}
			set
			{
				if ((this._TrangThaiThanhToan != value))
				{
					this.OnTrangThaiThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiThanhToan = value;
					this.SendPropertyChanged("TrangThaiThanhToan");
					this.OnTrangThaiThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucThanhToan", DbType="NVarChar(70)")]
		public string HinhThucThanhToan
		{
			get
			{
				return this._HinhThucThanhToan;
			}
			set
			{
				if ((this._HinhThucThanhToan != value))
				{
					this.OnHinhThucThanhToanChanging(value);
					this.SendPropertyChanging();
					this._HinhThucThanhToan = value;
					this.SendPropertyChanged("HinhThucThanhToan");
					this.OnHinhThucThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDonHang", DbType="NVarChar(40)")]
		public string TrangThaiDonHang
		{
			get
			{
				return this._TrangThaiDonHang;
			}
			set
			{
				if ((this._TrangThaiDonHang != value))
				{
					this.OnTrangThaiDonHangChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiDonHang = value;
					this.SendPropertyChanged("TrangThaiDonHang");
					this.OnTrangThaiDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiGiaoHang", DbType="NVarChar(50)")]
		public string DiaChiGiaoHang
		{
			get
			{
				return this._DiaChiGiaoHang;
			}
			set
			{
				if ((this._DiaChiGiaoHang != value))
				{
					this.OnDiaChiGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._DiaChiGiaoHang = value;
					this.SendPropertyChanged("DiaChiGiaoHang");
					this.OnDiaChiGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVoucher", DbType="NVarChar(20)")]
		public string MaVoucher
		{
			get
			{
				return this._MaVoucher;
			}
			set
			{
				if ((this._MaVoucher != value))
				{
					this.OnMaVoucherChanging(value);
					this.SendPropertyChanging();
					this._MaVoucher = value;
					this.SendPropertyChanged("MaVoucher");
					this.OnMaVoucherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecipientPhone", DbType="NVarChar(13)")]
		public string RecipientPhone
		{
			get
			{
				return this._RecipientPhone;
			}
			set
			{
				if ((this._RecipientPhone != value))
				{
					this.OnRecipientPhoneChanging(value);
					this.SendPropertyChanging();
					this._RecipientPhone = value;
					this.SendPropertyChanged("RecipientPhone");
					this.OnRecipientPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="donhang_chitietdonhang", Storage="_chitietdonhangs", ThisKey="MaDonHang", OtherKey="MaDonHang")]
		public EntitySet<chitietdonhang> chitietdonhangs
		{
			get
			{
				return this._chitietdonhangs;
			}
			set
			{
				this._chitietdonhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_donhang", Storage="_khachhang", ThisKey="MaKhachHang", OtherKey="MaKH", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.donhangs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.donhangs.Add(this);
						this._MaKhachHang = value.MaKH;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.donhang = this;
		}
		
		private void detach_chitietdonhangs(chitietdonhang entity)
		{
			this.SendPropertyChanging();
			entity.donhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.feedback")]
	public partial class feedback : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Mafeedback;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<int> _MaChiTietDH;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _ThoiGianfeedback;
		
		private System.Nullable<double> _DanhGia;
		
		private EntityRef<chitietdonhang> _chitietdonhang;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMafeedbackChanging(int value);
    partial void OnMafeedbackChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnMaChiTietDHChanging(System.Nullable<int> value);
    partial void OnMaChiTietDHChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnThoiGianfeedbackChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianfeedbackChanged();
    partial void OnDanhGiaChanging(System.Nullable<double> value);
    partial void OnDanhGiaChanged();
    #endregion
		
		public feedback()
		{
			this._chitietdonhang = default(EntityRef<chitietdonhang>);
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mafeedback", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Mafeedback
		{
			get
			{
				return this._Mafeedback;
			}
			set
			{
				if ((this._Mafeedback != value))
				{
					this.OnMafeedbackChanging(value);
					this.SendPropertyChanging();
					this._Mafeedback = value;
					this.SendPropertyChanged("Mafeedback");
					this.OnMafeedbackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietDH", DbType="Int")]
		public System.Nullable<int> MaChiTietDH
		{
			get
			{
				return this._MaChiTietDH;
			}
			set
			{
				if ((this._MaChiTietDH != value))
				{
					if (this._chitietdonhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChiTietDHChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietDH = value;
					this.SendPropertyChanged("MaChiTietDH");
					this.OnMaChiTietDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianfeedback", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianfeedback
		{
			get
			{
				return this._ThoiGianfeedback;
			}
			set
			{
				if ((this._ThoiGianfeedback != value))
				{
					this.OnThoiGianfeedbackChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianfeedback = value;
					this.SendPropertyChanged("ThoiGianfeedback");
					this.OnThoiGianfeedbackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGia", DbType="Float")]
		public System.Nullable<double> DanhGia
		{
			get
			{
				return this._DanhGia;
			}
			set
			{
				if ((this._DanhGia != value))
				{
					this.OnDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DanhGia = value;
					this.SendPropertyChanged("DanhGia");
					this.OnDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chitietdonhang_feedback", Storage="_chitietdonhang", ThisKey="MaChiTietDH", OtherKey="MaChiTiet", IsForeignKey=true)]
		public chitietdonhang chitietdonhang
		{
			get
			{
				return this._chitietdonhang.Entity;
			}
			set
			{
				chitietdonhang previousValue = this._chitietdonhang.Entity;
				if (((previousValue != value) 
							|| (this._chitietdonhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chitietdonhang.Entity = null;
						previousValue.feedbacks.Remove(this);
					}
					this._chitietdonhang.Entity = value;
					if ((value != null))
					{
						value.feedbacks.Add(this);
						this._MaChiTietDH = value.MaChiTiet;
					}
					else
					{
						this._MaChiTietDH = default(Nullable<int>);
					}
					this.SendPropertyChanged("chitietdonhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_feedback", Storage="_khachhang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.feedbacks.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.feedbacks.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.giohang")]
	public partial class giohang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGioHang;
		
		private System.Nullable<int> _MaKhachHang;
		
		private System.Nullable<int> _MaChiTietSanPham;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<chitietsanpham> _chitietsanpham;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGioHangChanging(int value);
    partial void OnMaGioHangChanged();
    partial void OnMaKhachHangChanging(System.Nullable<int> value);
    partial void OnMaKhachHangChanged();
    partial void OnMaChiTietSanPhamChanging(System.Nullable<int> value);
    partial void OnMaChiTietSanPhamChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public giohang()
		{
			this._chitietsanpham = default(EntityRef<chitietsanpham>);
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGioHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGioHang
		{
			get
			{
				return this._MaGioHang;
			}
			set
			{
				if ((this._MaGioHang != value))
				{
					this.OnMaGioHangChanging(value);
					this.SendPropertyChanging();
					this._MaGioHang = value;
					this.SendPropertyChanged("MaGioHang");
					this.OnMaGioHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int")]
		public System.Nullable<int> MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietSanPham", DbType="Int")]
		public System.Nullable<int> MaChiTietSanPham
		{
			get
			{
				return this._MaChiTietSanPham;
			}
			set
			{
				if ((this._MaChiTietSanPham != value))
				{
					if (this._chitietsanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChiTietSanPhamChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietSanPham = value;
					this.SendPropertyChanged("MaChiTietSanPham");
					this.OnMaChiTietSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chitietsanpham_giohang", Storage="_chitietsanpham", ThisKey="MaChiTietSanPham", OtherKey="MaChiTiet", IsForeignKey=true)]
		public chitietsanpham chitietsanpham
		{
			get
			{
				return this._chitietsanpham.Entity;
			}
			set
			{
				chitietsanpham previousValue = this._chitietsanpham.Entity;
				if (((previousValue != value) 
							|| (this._chitietsanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chitietsanpham.Entity = null;
						previousValue.giohangs.Remove(this);
					}
					this._chitietsanpham.Entity = value;
					if ((value != null))
					{
						value.giohangs.Add(this);
						this._MaChiTietSanPham = value.MaChiTiet;
					}
					else
					{
						this._MaChiTietSanPham = default(Nullable<int>);
					}
					this.SendPropertyChanged("chitietsanpham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_giohang", Storage="_khachhang", ThisKey="MaKhachHang", OtherKey="MaKH", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.giohangs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.giohangs.Add(this);
						this._MaKhachHang = value.MaKH;
					}
					else
					{
						this._MaKhachHang = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hinhanh")]
	public partial class hinhanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHinhAnh;
		
		private System.Nullable<int> _MaSp;
		
		private string _Hinhanh1;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHinhAnhChanging(int value);
    partial void OnMaHinhAnhChanged();
    partial void OnMaSpChanging(System.Nullable<int> value);
    partial void OnMaSpChanged();
    partial void OnHinhanh1Changing(string value);
    partial void OnHinhanh1Changed();
    #endregion
		
		public hinhanh()
		{
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhAnh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHinhAnh
		{
			get
			{
				return this._MaHinhAnh;
			}
			set
			{
				if ((this._MaHinhAnh != value))
				{
					this.OnMaHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._MaHinhAnh = value;
					this.SendPropertyChanged("MaHinhAnh");
					this.OnMaHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSp", DbType="Int")]
		public System.Nullable<int> MaSp
		{
			get
			{
				return this._MaSp;
			}
			set
			{
				if ((this._MaSp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSpChanging(value);
					this.SendPropertyChanging();
					this._MaSp = value;
					this.SendPropertyChanged("MaSp");
					this.OnMaSpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Hinhanh", Storage="_Hinhanh1", DbType="NVarChar(200)")]
		public string Hinhanh1
		{
			get
			{
				return this._Hinhanh1;
			}
			set
			{
				if ((this._Hinhanh1 != value))
				{
					this.OnHinhanh1Changing(value);
					this.SendPropertyChanging();
					this._Hinhanh1 = value;
					this.SendPropertyChanged("Hinhanh1");
					this.OnHinhanh1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_hinhanh", Storage="_sanpham", ThisKey="MaSp", OtherKey="MaSP", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.hinhanhs.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.hinhanhs.Add(this);
						this._MaSp = value.MaSP;
					}
					else
					{
						this._MaSp = default(Nullable<int>);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kichthuoc")]
	public partial class kichthuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKichThuoc;
		
		private string _TenKichThuoc;
		
		private EntitySet<chitietsanpham> _chitietsanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKichThuocChanging(int value);
    partial void OnMaKichThuocChanged();
    partial void OnTenKichThuocChanging(string value);
    partial void OnTenKichThuocChanged();
    #endregion
		
		public kichthuoc()
		{
			this._chitietsanphams = new EntitySet<chitietsanpham>(new Action<chitietsanpham>(this.attach_chitietsanphams), new Action<chitietsanpham>(this.detach_chitietsanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKichThuoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKichThuoc
		{
			get
			{
				return this._MaKichThuoc;
			}
			set
			{
				if ((this._MaKichThuoc != value))
				{
					this.OnMaKichThuocChanging(value);
					this.SendPropertyChanging();
					this._MaKichThuoc = value;
					this.SendPropertyChanged("MaKichThuoc");
					this.OnMaKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKichThuoc", DbType="NVarChar(20)")]
		public string TenKichThuoc
		{
			get
			{
				return this._TenKichThuoc;
			}
			set
			{
				if ((this._TenKichThuoc != value))
				{
					this.OnTenKichThuocChanging(value);
					this.SendPropertyChanging();
					this._TenKichThuoc = value;
					this.SendPropertyChanged("TenKichThuoc");
					this.OnTenKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="kichthuoc_chitietsanpham", Storage="_chitietsanphams", ThisKey="MaKichThuoc", OtherKey="MaKichThuoc")]
		public EntitySet<chitietsanpham> chitietsanphams
		{
			get
			{
				return this._chitietsanphams;
			}
			set
			{
				this._chitietsanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietsanphams(chitietsanpham entity)
		{
			this.SendPropertyChanging();
			entity.kichthuoc = this;
		}
		
		private void detach_chitietsanphams(chitietsanpham entity)
		{
			this.SendPropertyChanging();
			entity.kichthuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TenKH;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private string _DiaChi;
		
		private string _Password_hs5;
		
		private string _GioiTinh;
		
		private string _TrangThai;
		
		private string _avatar;
		
		private string _Role;
		
		private EntitySet<donhang> _donhangs;
		
		private EntitySet<feedback> _feedbacks;
		
		private EntitySet<giohang> _giohangs;
		
		private EntitySet<voucher_khachhang> _voucher_khachhangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnPassword_hs5Changing(string value);
    partial void OnPassword_hs5Changed();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    #endregion
		
		public khachhang()
		{
			this._donhangs = new EntitySet<donhang>(new Action<donhang>(this.attach_donhangs), new Action<donhang>(this.detach_donhangs));
			this._feedbacks = new EntitySet<feedback>(new Action<feedback>(this.attach_feedbacks), new Action<feedback>(this.detach_feedbacks));
			this._giohangs = new EntitySet<giohang>(new Action<giohang>(this.attach_giohangs), new Action<giohang>(this.detach_giohangs));
			this._voucher_khachhangs = new EntitySet<voucher_khachhang>(new Action<voucher_khachhang>(this.attach_voucher_khachhangs), new Action<voucher_khachhang>(this.detach_voucher_khachhangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(15)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(60)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password_hs5", DbType="NVarChar(100)")]
		public string Password_hs5
		{
			get
			{
				return this._Password_hs5;
			}
			set
			{
				if ((this._Password_hs5 != value))
				{
					this.OnPassword_hs5Changing(value);
					this.SendPropertyChanging();
					this._Password_hs5 = value;
					this.SendPropertyChanged("Password_hs5");
					this.OnPassword_hs5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(15)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(100)")]
		public string avatar
		{
			get
			{
				return this._avatar;
			}
			set
			{
				if ((this._avatar != value))
				{
					this.OnavatarChanging(value);
					this.SendPropertyChanging();
					this._avatar = value;
					this.SendPropertyChanged("avatar");
					this.OnavatarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(15)")]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_donhang", Storage="_donhangs", ThisKey="MaKH", OtherKey="MaKhachHang")]
		public EntitySet<donhang> donhangs
		{
			get
			{
				return this._donhangs;
			}
			set
			{
				this._donhangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_feedback", Storage="_feedbacks", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<feedback> feedbacks
		{
			get
			{
				return this._feedbacks;
			}
			set
			{
				this._feedbacks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_giohang", Storage="_giohangs", ThisKey="MaKH", OtherKey="MaKhachHang")]
		public EntitySet<giohang> giohangs
		{
			get
			{
				return this._giohangs;
			}
			set
			{
				this._giohangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_voucher_khachhang", Storage="_voucher_khachhangs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<voucher_khachhang> voucher_khachhangs
		{
			get
			{
				return this._voucher_khachhangs;
			}
			set
			{
				this._voucher_khachhangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_donhangs(donhang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_donhangs(donhang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_feedbacks(feedback entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_feedbacks(feedback entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_giohangs(giohang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_giohangs(giohang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_voucher_khachhangs(voucher_khachhang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_voucher_khachhangs(voucher_khachhang entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mausac")]
	public partial class mausac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMau;
		
		private string _TenMau;
		
		private string _HEXCODE;
		
		private EntitySet<chitietsanpham> _chitietsanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMauChanging(int value);
    partial void OnMaMauChanged();
    partial void OnTenMauChanging(string value);
    partial void OnTenMauChanged();
    partial void OnHEXCODEChanging(string value);
    partial void OnHEXCODEChanged();
    #endregion
		
		public mausac()
		{
			this._chitietsanphams = new EntitySet<chitietsanpham>(new Action<chitietsanpham>(this.attach_chitietsanphams), new Action<chitietsanpham>(this.detach_chitietsanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMau", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaMau
		{
			get
			{
				return this._MaMau;
			}
			set
			{
				if ((this._MaMau != value))
				{
					this.OnMaMauChanging(value);
					this.SendPropertyChanging();
					this._MaMau = value;
					this.SendPropertyChanged("MaMau");
					this.OnMaMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMau", DbType="NVarChar(20)")]
		public string TenMau
		{
			get
			{
				return this._TenMau;
			}
			set
			{
				if ((this._TenMau != value))
				{
					this.OnTenMauChanging(value);
					this.SendPropertyChanging();
					this._TenMau = value;
					this.SendPropertyChanged("TenMau");
					this.OnTenMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEXCODE", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string HEXCODE
		{
			get
			{
				return this._HEXCODE;
			}
			set
			{
				if ((this._HEXCODE != value))
				{
					this.OnHEXCODEChanging(value);
					this.SendPropertyChanging();
					this._HEXCODE = value;
					this.SendPropertyChanged("HEXCODE");
					this.OnHEXCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mausac_chitietsanpham", Storage="_chitietsanphams", ThisKey="MaMau", OtherKey="MaMau")]
		public EntitySet<chitietsanpham> chitietsanphams
		{
			get
			{
				return this._chitietsanphams;
			}
			set
			{
				this._chitietsanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietsanphams(chitietsanpham entity)
		{
			this.SendPropertyChanging();
			entity.mausac = this;
		}
		
		private void detach_chitietsanphams(chitietsanpham entity)
		{
			this.SendPropertyChanging();
			entity.mausac = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaSP;
		
		private string _TenSP;
		
		private double _Gia;
		
		private System.Nullable<double> _PhanTramGiamGia;
		
		private string _MoTa;
		
		private int _MaDanhMuc;
		
		private int _MaNhaCungCap;
		
		private string _TrinhTrang;
		
		private EntitySet<chitietsanpham> _chitietsanphams;
		
		private EntitySet<hinhanh> _hinhanhs;
		
		private EntityRef<danhmuc> _danhmuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(int value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnGiaChanging(double value);
    partial void OnGiaChanged();
    partial void OnPhanTramGiamGiaChanging(System.Nullable<double> value);
    partial void OnPhanTramGiamGiaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnMaDanhMucChanging(int value);
    partial void OnMaDanhMucChanged();
    partial void OnMaNhaCungCapChanging(int value);
    partial void OnMaNhaCungCapChanged();
    partial void OnTrinhTrangChanging(string value);
    partial void OnTrinhTrangChanged();
    #endregion
		
		public sanpham()
		{
			this._chitietsanphams = new EntitySet<chitietsanpham>(new Action<chitietsanpham>(this.attach_chitietsanphams), new Action<chitietsanpham>(this.detach_chitietsanphams));
			this._hinhanhs = new EntitySet<hinhanh>(new Action<hinhanh>(this.attach_hinhanhs), new Action<hinhanh>(this.detach_hinhanhs));
			this._danhmuc = default(EntityRef<danhmuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float NOT NULL")]
		public double Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanTramGiamGia", DbType="Float")]
		public System.Nullable<double> PhanTramGiamGia
		{
			get
			{
				return this._PhanTramGiamGia;
			}
			set
			{
				if ((this._PhanTramGiamGia != value))
				{
					this.OnPhanTramGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._PhanTramGiamGia = value;
					this.SendPropertyChanged("PhanTramGiamGia");
					this.OnPhanTramGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanhMuc", DbType="Int NOT NULL")]
		public int MaDanhMuc
		{
			get
			{
				return this._MaDanhMuc;
			}
			set
			{
				if ((this._MaDanhMuc != value))
				{
					if (this._danhmuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDanhMucChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMuc = value;
					this.SendPropertyChanged("MaDanhMuc");
					this.OnMaDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhaCungCap", DbType="Int NOT NULL")]
		public int MaNhaCungCap
		{
			get
			{
				return this._MaNhaCungCap;
			}
			set
			{
				if ((this._MaNhaCungCap != value))
				{
					this.OnMaNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._MaNhaCungCap = value;
					this.SendPropertyChanged("MaNhaCungCap");
					this.OnMaNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhTrang", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TrinhTrang
		{
			get
			{
				return this._TrinhTrang;
			}
			set
			{
				if ((this._TrinhTrang != value))
				{
					this.OnTrinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TrinhTrang = value;
					this.SendPropertyChanged("TrinhTrang");
					this.OnTrinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_chitietsanpham", Storage="_chitietsanphams", ThisKey="MaSP", OtherKey="MaSP")]
		public EntitySet<chitietsanpham> chitietsanphams
		{
			get
			{
				return this._chitietsanphams;
			}
			set
			{
				this._chitietsanphams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_hinhanh", Storage="_hinhanhs", ThisKey="MaSP", OtherKey="MaSp")]
		public EntitySet<hinhanh> hinhanhs
		{
			get
			{
				return this._hinhanhs;
			}
			set
			{
				this._hinhanhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_sanpham", Storage="_danhmuc", ThisKey="MaDanhMuc", OtherKey="MaDanhMuc", IsForeignKey=true)]
		public danhmuc danhmuc
		{
			get
			{
				return this._danhmuc.Entity;
			}
			set
			{
				danhmuc previousValue = this._danhmuc.Entity;
				if (((previousValue != value) 
							|| (this._danhmuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._danhmuc.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._danhmuc.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._MaDanhMuc = value.MaDanhMuc;
					}
					else
					{
						this._MaDanhMuc = default(int);
					}
					this.SendPropertyChanged("danhmuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietsanphams(chitietsanpham entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_chitietsanphams(chitietsanpham entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
		
		private void attach_hinhanhs(hinhanh entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_hinhanhs(hinhanh entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _email_verified_at;
		
		private string _password;
		
		private string _remember_token;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private System.Nullable<System.DateTime> _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onemail_verified_atChanging(System.Nullable<System.DateTime> value);
    partial void Onemail_verified_atChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onremember_tokenChanging(string value);
    partial void Onremember_tokenChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_verified_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> email_verified_at
		{
			get
			{
				return this._email_verified_at;
			}
			set
			{
				if ((this._email_verified_at != value))
				{
					this.Onemail_verified_atChanging(value);
					this.SendPropertyChanging();
					this._email_verified_at = value;
					this.SendPropertyChanged("email_verified_at");
					this.Onemail_verified_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remember_token", DbType="NVarChar(100)")]
		public string remember_token
		{
			get
			{
				return this._remember_token;
			}
			set
			{
				if ((this._remember_token != value))
				{
					this.Onremember_tokenChanging(value);
					this.SendPropertyChanging();
					this._remember_token = value;
					this.SendPropertyChanged("remember_token");
					this.Onremember_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.voucher")]
	public partial class voucher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_VOUCHER;
		
		private string _Ten_VOUCHER;
		
		private System.Nullable<double> _PhanTramGiam;
		
		private System.Nullable<double> _DonToiThieu;
		
		private System.Nullable<double> _GiamToiDa;
		
		private System.Nullable<int> _SoLuongVOUCHER;
		
		private System.Nullable<System.DateTime> _Ngaybatdau;
		
		private System.Nullable<System.DateTime> _Ngayketthuc;
		
		private EntitySet<voucher_khachhang> _voucher_khachhangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_VOUCHERChanging(string value);
    partial void OnMA_VOUCHERChanged();
    partial void OnTen_VOUCHERChanging(string value);
    partial void OnTen_VOUCHERChanged();
    partial void OnPhanTramGiamChanging(System.Nullable<double> value);
    partial void OnPhanTramGiamChanged();
    partial void OnDonToiThieuChanging(System.Nullable<double> value);
    partial void OnDonToiThieuChanged();
    partial void OnGiamToiDaChanging(System.Nullable<double> value);
    partial void OnGiamToiDaChanged();
    partial void OnSoLuongVOUCHERChanging(System.Nullable<int> value);
    partial void OnSoLuongVOUCHERChanged();
    partial void OnNgaybatdauChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaybatdauChanged();
    partial void OnNgayketthucChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayketthucChanged();
    #endregion
		
		public voucher()
		{
			this._voucher_khachhangs = new EntitySet<voucher_khachhang>(new Action<voucher_khachhang>(this.attach_voucher_khachhangs), new Action<voucher_khachhang>(this.detach_voucher_khachhangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_VOUCHER", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_VOUCHER
		{
			get
			{
				return this._MA_VOUCHER;
			}
			set
			{
				if ((this._MA_VOUCHER != value))
				{
					this.OnMA_VOUCHERChanging(value);
					this.SendPropertyChanging();
					this._MA_VOUCHER = value;
					this.SendPropertyChanged("MA_VOUCHER");
					this.OnMA_VOUCHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_VOUCHER", DbType="Char(50)")]
		public string Ten_VOUCHER
		{
			get
			{
				return this._Ten_VOUCHER;
			}
			set
			{
				if ((this._Ten_VOUCHER != value))
				{
					this.OnTen_VOUCHERChanging(value);
					this.SendPropertyChanging();
					this._Ten_VOUCHER = value;
					this.SendPropertyChanged("Ten_VOUCHER");
					this.OnTen_VOUCHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanTramGiam", DbType="Float")]
		public System.Nullable<double> PhanTramGiam
		{
			get
			{
				return this._PhanTramGiam;
			}
			set
			{
				if ((this._PhanTramGiam != value))
				{
					this.OnPhanTramGiamChanging(value);
					this.SendPropertyChanging();
					this._PhanTramGiam = value;
					this.SendPropertyChanged("PhanTramGiam");
					this.OnPhanTramGiamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonToiThieu", DbType="Float")]
		public System.Nullable<double> DonToiThieu
		{
			get
			{
				return this._DonToiThieu;
			}
			set
			{
				if ((this._DonToiThieu != value))
				{
					this.OnDonToiThieuChanging(value);
					this.SendPropertyChanging();
					this._DonToiThieu = value;
					this.SendPropertyChanged("DonToiThieu");
					this.OnDonToiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamToiDa", DbType="Float")]
		public System.Nullable<double> GiamToiDa
		{
			get
			{
				return this._GiamToiDa;
			}
			set
			{
				if ((this._GiamToiDa != value))
				{
					this.OnGiamToiDaChanging(value);
					this.SendPropertyChanging();
					this._GiamToiDa = value;
					this.SendPropertyChanged("GiamToiDa");
					this.OnGiamToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongVOUCHER", DbType="Int")]
		public System.Nullable<int> SoLuongVOUCHER
		{
			get
			{
				return this._SoLuongVOUCHER;
			}
			set
			{
				if ((this._SoLuongVOUCHER != value))
				{
					this.OnSoLuongVOUCHERChanging(value);
					this.SendPropertyChanging();
					this._SoLuongVOUCHER = value;
					this.SendPropertyChanged("SoLuongVOUCHER");
					this.OnSoLuongVOUCHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaybatdau", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaybatdau
		{
			get
			{
				return this._Ngaybatdau;
			}
			set
			{
				if ((this._Ngaybatdau != value))
				{
					this.OnNgaybatdauChanging(value);
					this.SendPropertyChanging();
					this._Ngaybatdau = value;
					this.SendPropertyChanged("Ngaybatdau");
					this.OnNgaybatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayketthuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayketthuc
		{
			get
			{
				return this._Ngayketthuc;
			}
			set
			{
				if ((this._Ngayketthuc != value))
				{
					this.OnNgayketthucChanging(value);
					this.SendPropertyChanging();
					this._Ngayketthuc = value;
					this.SendPropertyChanged("Ngayketthuc");
					this.OnNgayketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="voucher_voucher_khachhang", Storage="_voucher_khachhangs", ThisKey="MA_VOUCHER", OtherKey="MA_VOUCHER")]
		public EntitySet<voucher_khachhang> voucher_khachhangs
		{
			get
			{
				return this._voucher_khachhangs;
			}
			set
			{
				this._voucher_khachhangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_voucher_khachhangs(voucher_khachhang entity)
		{
			this.SendPropertyChanging();
			entity.voucher = this;
		}
		
		private void detach_voucher_khachhangs(voucher_khachhang entity)
		{
			this.SendPropertyChanging();
			entity.voucher = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.voucher_khachhang")]
	public partial class voucher_khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _MA_VOUCHER;
		
		private string _note;
		
		private EntityRef<voucher> _voucher;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnMA_VOUCHERChanging(string value);
    partial void OnMA_VOUCHERChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    #endregion
		
		public voucher_khachhang()
		{
			this._voucher = default(EntityRef<voucher>);
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_VOUCHER", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_VOUCHER
		{
			get
			{
				return this._MA_VOUCHER;
			}
			set
			{
				if ((this._MA_VOUCHER != value))
				{
					if (this._voucher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_VOUCHERChanging(value);
					this.SendPropertyChanging();
					this._MA_VOUCHER = value;
					this.SendPropertyChanged("MA_VOUCHER");
					this.OnMA_VOUCHERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(15)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="voucher_voucher_khachhang", Storage="_voucher", ThisKey="MA_VOUCHER", OtherKey="MA_VOUCHER", IsForeignKey=true)]
		public voucher voucher
		{
			get
			{
				return this._voucher.Entity;
			}
			set
			{
				voucher previousValue = this._voucher.Entity;
				if (((previousValue != value) 
							|| (this._voucher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._voucher.Entity = null;
						previousValue.voucher_khachhangs.Remove(this);
					}
					this._voucher.Entity = value;
					if ((value != null))
					{
						value.voucher_khachhangs.Add(this);
						this._MA_VOUCHER = value.MA_VOUCHER;
					}
					else
					{
						this._MA_VOUCHER = default(string);
					}
					this.SendPropertyChanged("voucher");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_voucher_khachhang", Storage="_khachhang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.voucher_khachhangs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.voucher_khachhangs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
